---
- hosts: jenkins
  become: yes
  tasks:
  
    - name: Install plugin
      jenkins_plugin:
        name: github-oauth
        url: http://localhost:8080
        url_username: admin
        url_password: admin
    
    - name: Restart Jenkins
      service:
        name: jenkins
        state: restarted
