---
- hosts: jenkins
  become: true
  tasks:
  - jenkins_job:
      config: "{{ lookup('file', 'templates/test.xml') }}"
      name: test
      password: admin
      url: http://localhost:8080
      user: admin
