---
- hosts: sonar
  become: true
  tasks:       
   - name: Install openjdk-11-jdk
     apt:
       name: openjdk-11-jdk
       state: present
       
   - name: Install python-psycopg2
     apt:
       name: python-psycopg2
       state: present
      
   - name: Download psql
     shell:
      cmd: sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" >> /etc/apt/sources.list.d/pgdg.list'
   - name: Add key
     shell:
      cmd: wget -q https://www.postgresql.org/media/keys/ACCC4CF8.asc -O - | apt-key add -
   - name: Install postgresql
     apt: 
      name: postgresql-9.5
      state: present
    
   - name: Install psql-contrib
     apt: 
      name: postgresql-contrib
      state: present
      
   
   - name: Enables password authentication method
     become: yes
     replace:
       dest: /etc/postgresql/9.5/main/pg_hba.conf
       regexp: "^local\\s*all\\s*all\\s*peer$"
       replace: "local   all             all            md5"

   - name: Reloads Postgres
     become: yes
     service:
       name: postgresql
       state: reloaded
   - name: Create sonar user in databse
     become_user: postgres
     postgresql_user:
       name: sonar
       password: sonar
       role_attr_flags: CREATEDB,NOSUPERUSER
      
   - name: Create sonar database
     become_user: postgres
     postgresql_db:
       name: sonar
       owner: sonar
      
