---
- hosts: sonar
  become: true
  tasks:
   - name: Download psql
     shell:
      cmd: sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" >> /etc/apt/sources.list.d/pgdg.list'
   - name: Add key
     shell:
      cmd: wget -q https://www.postgresql.org/media/keys/ACCC4CF8.asc -O - | apt-key add -
   - name: Install psql
     install: pkg='postgresql postgresql-contrib'
