---
- hosts: sonar
  become: true
  tasks:
  - name: Install wget
    apt:
      name: wget
      state: present

  - name: Install openjdk
    apt:
      name: default-jdk
      state: present
      
  - name: Install python-psycopg2
    apt:
      name: python-psycopg2
      state: present
      
  - name: Create the sonar user for running the SonarQube services
    become: yes
    user:
      name: sonar
      comment: System user for running SonarQube
    
  - name: Create sonar database
    become: yes
    become_user: postgres
    postgresql_db:
      name: sonar
      
  - name: Create sonar directory
    become: yes
    file:
      path: "/opt/sonar"
      state: directory

  - name: Extract SonarQube
    become: yes
    unarchive:
      src: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-8.0.zip
      dest: "/opt/sonar/"
      copy: no
      owner: sonar
