---
- hosts: sonar
  become: true
  tasks:
  - name: Install wget
    apt:
      name: wget
      state: present

  - name: Install openjdk
    apt:
      name: default-jdk
      state: present
  - name: Download sonarqube
    shell:
     chdir: /opt/sonarqube
     cmd: wget https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-8.0.zip
  - name: Unzip the package
    shell:
     cmd: unzip sonarqube-8.0.zip
     chdir: sonarqube-8.0
